 
server:  
  port: ${PORT:2222}

spring:  
  application:
    name: account-service
  h2:
    console:
      enabled: true
      path: /h2  

  boot:
    admin:
      client:
        url:
        - http://localhost:1111        

eureka:  
  client:
    serviceUrl:
      defaultZone: ${DISCOVERY_URL:http://localhost:8761}/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
      
ribbon:
  eureka:
    enabled: true   
    